### PR TITLE
Shear

### PR DESCRIPTION
**Pull request by Trebgarta**
just copy pasted scale and mdified it for 3D shear. Perhaps you'd like 3 cpml.vec2 s? Just wanted to go the simplest route for first PR.

[This](http://web.iitd.ac.in/~hegde/cad/lecture/L6_3dtrans.pdf)(pdf) is my source BTW.

### CODE REVIEW

**Comment by karai17** [comment]
Shouldn't the shear function do the applicable math? Passing in 6 arguments seems less useful.

**Comment by Trebgarta** [comment]
I don't quite get what you mean. There are 6 independent variables, 2 axii for each 3 plane to "shear" on, as fas as I understand. Only math I can think of would be to shear an object on an arbitrary vector?

**Comment by karai17** [comment]
Hm, maybe I am misunderstanding then. I'll let @shakesoda look at this.

**Comment by shakesoda** [comment]
give the arguments default values (0) and it looks fine to me.

I've been meaning to add this for a while, thanks!

**Comment by karai17** [comment]
Could you place each local on a new line and remove the semicolons so that the code matches the rest of cpml's style?

thanks!

**Comment by karai17** [comment]
Thanks <3

**Pull request merged**
